language: php

matrix:
  include:
  - php: "7.3"
    env: LARAVEL_VERSION="^6.0" RUN_CS_FIXER=1
  - php: "7.4"
    env: LARAVEL_VERSION="^7.0"
  - php: "8.0"
    env: LARAVEL_VERSION="^8.0"
  - php: "8.0"
    env: LARAVEL_VERSION="^9.0"
  - php: "8.1"
    env: LARAVEL_VERSION="^9.0"

sudo: false

install:
  - composer require "illuminate/contracts:${LARAVEL_VERSION}" "swisnl/illuminate-collections:${LARAVEL_VERSION}" --no-update --no-interaction
  - travis_retry composer install --no-interaction --prefer-dist

script:
  - if [ "$RUN_CS_FIXER" ] ; then vendor/bin/php-cs-fixer fix -v --dry-run --using-cache=no ; fi
  - XDEBUG_MODE=coverage vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - |
    composer global require --no-interaction --prefer-dist scrutinizer/ocular
    ~/.config/composer/vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover

branches:
  only:
    - 1.x
    - master
